// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCguCM735EOeX9VSW9V-O8tekcgv7cz-Mg',
    appId: '1:950423524502:web:ac8e4ea00cad212f335eb7',
    messagingSenderId: '950423524502',
    projectId: 'change-of-love',
    authDomain: 'change-of-love.firebaseapp.com',
    storageBucket: 'change-of-love.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgW1lGYc9pLPnUh-PZJL6bzBkdcAc3NOs',
    appId: '1:950423524502:android:8bfb3fada29f6c28335eb7',
    messagingSenderId: '950423524502',
    projectId: 'change-of-love',
    storageBucket: 'change-of-love.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeEek7lJOnqqqV7G_0b3mTQocjCHMBrEM',
    appId: '1:950423524502:ios:30aea0e21b455860335eb7',
    messagingSenderId: '950423524502',
    projectId: 'change-of-love',
    storageBucket: 'change-of-love.appspot.com',
    iosBundleId: 'com.example.changeOfLove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeEek7lJOnqqqV7G_0b3mTQocjCHMBrEM',
    appId: '1:950423524502:ios:c2b697dab1527970335eb7',
    messagingSenderId: '950423524502',
    projectId: 'change-of-love',
    storageBucket: 'change-of-love.appspot.com',
    iosBundleId: 'com.example.changeOfLove.RunnerTests',
  );
}
